admin:
  ip: 0.0.0.0
  port: 9990

# use the filesystem namer, read from the local /disco directory
namers:
- kind: io.l5d.fs
  rootDir: /etc/linkerd/disco

usage:
  orgId: linkerd-examples-aws

routers:
- protocol: http
  servers:
  - port: 4140
    ip: 0.0.0.0
  dtab: |
    /svc => /#/io.l5d.fs;
